blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://mormubis.github.io/elo/
    about: Read the API documentation
  - name: Discussions
    url: https://github.com/mormubis/elo/discussions
    about: Ask questions or share ideas
